name: cd

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish_to_pypi:
    name: publish to pypi on new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JRubics/poetry-publish@v1.16
        name: Build and publish to PyPI
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}